version: 2.1

parameters:
  new_openssl_commit:
    type: boolean
    default: false

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  debian_arm64:
    description: Build ARM64 benchmarking image on arm machine
    machine:
      image: 'ubuntu-2004:202101-01'
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: Build docker image and test
          command: |
            uname -a
            pwd
            ls -l
            docker build -t oqs-mperf-arm64 -f Dockerfile-arm64 .
            docker run -it oqs-mperf-arm64 /opt/test/selftest.sh
          working_directory: perf
      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
              - equal: [ true, << pipeline.parameters.new_openssl_commit >> ]
          steps:
            - run:
                name: Push image
                command: |
                  docker tag oqs-mperf-arm64 $TARGETNAME/oqs-perf:latest-arm64 &&
                  docker push $TARGETNAME/oqs-perf:latest-arm64

  debian_x64:
    description: A template for building and pushing OQS performance testing Docker image on Ubuntu Bionic that depend on OQS-OpenSSL
    docker:
      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - setup_remote_docker
      - run:
          name: Authenticate to Docker
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: Build and test profiling image
          command: |
            # The CircleCI executor offers 35 cores, but using
            # all of them might exhaust memory
            docker build --build-arg MAKE_DEFINES="-j 18" -t oqs-mperf . &&
            docker run -it oqs-mperf /opt/test/selftest.sh
          working_directory: perf
      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
              - equal: [ true, << pipeline.parameters.new_openssl_commit >> ]
          steps:
            - run:
                name: Push image
                command: |
                  docker tag oqs-mperf $TARGETNAME/oqs-perf:latest-amd64 &&
                  docker push $TARGETNAME/oqs-perf:latest-amd64 
  merge:
    description: merging multiple architecture docker images into one multiarch image
    docker:
      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - setup_remote_docker
      - run:
          name: Authenticate to Docker
          command: echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
              - equal: [ true, << pipeline.parameters.new_openssl_commit >> ]
          steps:
            - run:
                name: Merge and push manifests to properly label multiarch image
                command: |
                   export DOCKER_CLI_EXPERIMENTAL=enabled
                   docker manifest create $TARGETNAME/oqs-perf:latest $TARGETNAME/oqs-perf:latest-amd64 $TARGETNAME/oqs-perf:latest-arm64
                   # if --platform is not properly honored in build, set it explicitly here
                   docker manifest annotate $TARGETNAME/oqs-perf:latest $TARGETNAME/oqs-perf:latest-arm64 --arch arm64
                   docker manifest push $TARGETNAME/oqs-perf:latest

workflows:
  version: 2.1
  build:
    jobs:
      - debian_x64:
          context: openquantumsafe
      - debian_arm64:
          context: openquantumsafe
      - merge:
          requires:
             - debian_x64
             - debian_arm64
          context: openquantumsafe
